### ISSUE TITLE
Clarification on query #8

### ISSUE THREAD

**Issue by jeffstade** [musa-509-fall-2021/assignment-01-intro-to-geographic-queries#1]
https://github.com/musa-509-fall-2021/assignment-01-intro-to-geographic-queries/blob/380e877c1aa3e92705f2082fdb000ea35a665830/query08.sql#L2

Does this refer to the most popular start station for trips that started between 7-10am? Or are you expecting us to look at start and end station data combined?

**Comment by mjumbewu** [comment]
Good question. I'll rephrase to make it the most popular _starting_ station.

The most popular station for starting _and_ ending might be a little more interesting to calculate, but I'm not sure I can think of a good operational reason that it might be relevant, so I hesitate to assign it.
